apps/task/urls.py
from django.conf.urls import patterns, url
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = patterns('',
                       url(r'^$', views.main, name='index'),
                       url(r'^edit_profile/$', views.edit_profile,
                           name='edit_profile'),
                       url(r'^request_list/$', views.request_list,
                           name='request_list'),
                       url(r'^request_list_ajax/$', views.request_list_ajax,
                           name='request_list_ajax'),
                       url(r'^login/$', auth_views.login, name='login'),
                       url(r'^logout/$', auth_views.logout, {
                           'next_page': '/'
                       }, name='logout'),
                       url(r'^update_profile/$', views.update_profile,
                           name='update_profile'),
                       url(r'^tasks/$', views.tasks, name='tasks'),
                       url(r'^edit_task$', views.edit_task, name='edit_task'),
                       url(r'^update_priority/$', views.update_priority,
                           name='update_priority'),
                       )

task/urls.py
from django.conf.urls import patterns, url
from . import views


urlpatterns = patterns('',
                       url(r'^$', views.main, name='index'),
                       url(r'^request_list/$', views.request_list,
                           name='request_list'),
                       url(r'^request_list_ajax/$', views.request_list_ajax,
                           name='request_list_ajax'),
                       url(r'^request_detail/(?P<identify>[0-9]+)/$',
                           views.request_detail,
                           name='request_detail'),
                       url(r'^login/$', views.login_view, name='login'),
                       url(r'^logout/$', views.logout_view,
                           name='logout'),
                       url(r'^update_profile/$', views.update_profile,
                           name='update_profile'),
                       )

testtask/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^images/(?P<path>.*)$', 'django.views.static.serve'),
                       url(r'^', include('apps.task.urls', namespace="task")),
                       url('^', include('django.contrib.auth.urls')),
                       ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/task/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.db import models
from PIL import Image, ImageOps

STATUS_CHOICES = (
    (1, u'Выполнено',),
    (2, u'Не выполнено'),
)


def number():
        task_count = Task.objects.count()
        if task_count is None:
            return 1
        else:
            return task_count + 1


class Profile(models.Model):
    url_height = models.PositiveIntegerField(editable=False, default=200)
    url_width = models.PositiveIntegerField(editable=False, default=200)
    user = models.ForeignKey(User, default=1)
    name = models.CharField(max_length=250, default="Eneter your name")
    last_name = models.CharField(max_length=250,
                                 default="Eneter your last name")
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='images/',
                              blank=True,
                              null=True)
    bio = models.TextField(blank=True, null=True, default=" ")

    email = models.EmailField(blank=True, null=True)
    jabber = models.CharField(max_length=250, blank=True, null=True)
    skype = models.CharField(max_length=250, blank=True, null=True)
    other_contacts = models.TextField(blank=True, null=True, default=" ")

    class Meta:
        verbose_name = "Profile"
        verbose_name_plural = "Profiles"

    def __unicode__(self):
        return self.last_name

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)
        if self.photo:
            image = Image.open(self.photo)
            imagefit = ImageOps.fit(image, (200, 200),
                                    Image.ANTIALIAS)
            imagefit.save(self.photo.path, 'JPEG', quality=75)


class Requests(models.Model):
    title = models.CharField(max_length=250, default='Http_request')
    request = models.TextField()
    path = models.CharField(max_length=250, blank=True, null=True)
    pub_date = models.DateTimeField(auto_now_add=True)
    priority = models.PositiveIntegerField(default=10)

    class Meta:
        ordering = ['priority', 'pub_date']

    def __unicode__(self):
        return self.title


class SavedSignals(models.Model):
    title = models.CharField(max_length=250)
    status = models.CharField(max_length=250)

    def __unicode__(self):
        return self.title


class Task(models.Model):
    user = models.ForeignKey(User)
    title = models.CharField(max_length=255)
    description = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    priority = models.IntegerField(default=number)
    status = models.PositiveIntegerField(choices=STATUS_CHOICES, default=2)

    class Meta:
        ordering = ['priority', '-pub_date']

    def __unicode__(self):
        return self.title

apps/task/forms.py
from django import forms
from django.contrib.auth.models import User
from models import Profile, Task
from widgets import DatePickerWidget


class ProfileForm(forms.ModelForm):
    id = forms.IntegerField(widget=forms.HiddenInput())
    name = forms.CharField(max_length=100,
                           min_length=3,
                           widget=forms.TextInput(
                               attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=100,
                                min_length=3,
                                widget=forms.TextInput(
                                    attrs={'class': 'form-control'}))
    date_of_birth = forms.DateField(widget=DatePickerWidget(
        params="dateFormat: 'yy-mm-dd', changeYear: true,"
               " defaultDate: 'c-25', yearRange: 'c-115:c'",
        attrs={'class': 'datepicker'}))
    photo = forms.ImageField(required=False,
                             widget=forms.FileInput)
    email = forms.EmailField(max_length=100,
                             widget=forms.TextInput(attrs={'class':
                                                           'form-control'}))
    jabber = forms.EmailField(max_length=100,
                              min_length=3,
                              widget=forms.TextInput(attrs={'class':
                                                            'form-control'}))
    skype = forms.CharField(max_length=100,
                            min_length=3,
                            widget=forms.TextInput(attrs={'class':
                                                          'form-control'}))
    other_contacts = forms.CharField(max_length=1000,
                                     required=False,
                                     widget=forms.Textarea(
                                         attrs={'class':
                                                'form-control'}))
    bio = forms.CharField(max_length=1000,
                          required=False,
                          widget=forms.Textarea(
                              attrs={'class': 'form-control'}))

    class Meta:
        model = Profile
        fields = ['id', 'name', 'last_name',
                  'date_of_birth', 'photo', 'bio',
                  'email', 'jabber', 'skype',
                  'other_contacts']


class TaskForm(forms.ModelForm):
    user = forms.ModelChoiceField(queryset=User.objects.all(), label="",
                                  widget=forms.HiddenInput())
    title = forms.CharField(max_length=100,
                            min_length=3,
                            widget=forms.TextInput(
                                attrs={'class': 'form-control'}))
    description = forms.CharField(min_length=3,
                                  widget=forms.Textarea(
                                      attrs={'class': 'form-control'}))

    class Meta:
        model = Task
        fields = ['user', 'title', 'description', 'status']

apps/task/views.py
# -*- coding: utf-8 -*-
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.http.response import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render
from models import Profile
from models import Requests, Task
from forms import ProfileForm, TaskForm
from django.views.decorators.http import require_POST
from django.core.urlresolvers import reverse
import json
from django.template.context import RequestContext


def main(request):
    profile = Profile.objects.first()
    user_form = ProfileForm(instance=profile)
    context = dict(profile=profile, user_form=user_form)
    return render(request, 'task/main.html', context)


@login_required()
def edit_profile(request):
    profile = Profile.objects.first()
    user_form = ProfileForm(instance=profile)
    context = dict(profile=profile, user_form=user_form)
    return render(request, 'task/edit_profile.html', context)


def request_list(request):
    return render(request, 'task/request_list.html')


def request_list_ajax(request):
    if request.is_ajax():
        data = serializers.serialize("json", Requests.objects.all()[:10])
        return HttpResponse(data, content_type="application/json")
    else:
        raise Http404


@login_required()
@require_POST
def update_profile(request):
    identify = request.POST.get('id')
    profile = Profile.objects.get(id=identify)
    form = ProfileForm(request.POST, request.FILES, instance=profile)
    if form.is_valid():
        form.save()
        profile = Profile.objects.get(id=int(identify))
        profile_to_json = {'status': "success",
                           'image_src': profile.photo.url
                           if profile.photo else ''}
    else:
        profile_to_json = {'status': "error",
                           'image_src': profile.photo.url
                           if profile.photo else ' '}

    return HttpResponse(json.dumps(profile_to_json),
                        content_type="application/json")


@login_required()
def tasks(request, template='task/task_list.html',
          page_template='task/entry_tasks.html',
          extra_context=None):
    form = TaskForm(initial={'user': request.user.id})
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Task has been created!')
    task = Task.objects.all()
    context = {
        'task': task,
        'form': form,
        'page_template': page_template
    }
    if request.is_ajax():
        template = page_template
    return render(request, template,
                  context, context_instance=RequestContext(request))


@require_POST
@login_required()
def edit_task(request):
    task = Task.objects.get(id=request.POST.get('id'))
    copy = request.POST.copy()
    copy['user'] = request.user.id
    form = TaskForm(copy, instance=task)
    if form.is_valid():
        form.save()
        messages.add_message(request, messages.SUCCESS,
                             'Task has been updated!')
    else:
        messages.add_message(request, messages.ERROR,
                             'Error: Task is not updated!')
    return HttpResponseRedirect(reverse('task:tasks'))


@login_required()
def update_priority(request):
    task_position_id = map(int, request.GET.getlist('positions[]'))
    for index, item in enumerate(task_position_id, start=1):
        task = Task.objects.get(id=item)
        task.priority = index
        task.save()
    return HttpResponse(status=200)

task/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.http.response import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from models import Profile
from models import Requests
from forms import LoginForm, ProfileForm
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.http import require_POST
import json


def main(request):
    profile = Profile.objects.first()
    user_form = ProfileForm(instance=profile)
    context = dict(profile=profile, user_form=user_form)
    return render(request, 'task/main.html', context)


def request_list(request):
    return render(request, 'task/request_list.html')


def request_list_ajax(request):
    if request.is_ajax():
        data = serializers.serialize("json", Requests.objects.all()[:10])
        return HttpResponse(data, content_type="application/json")
    else:
        raise Http404


@login_required(login_url='/login/')
def request_detail(request, identify):
    obj = get_object_or_404(Requests, pk=identify)
    context = dict(obj=obj)
    return render(request, 'task/request_detail.html', context)


@login_required(login_url='/login/')
@require_POST
def update_profile(request):
    identify = request.POST.get('id')
    profile = Profile.objects.get(id=identify)
    form = ProfileForm(request.POST, request.FILES, instance=profile)
    if form.is_valid():
        form.save()
        profile = Profile.objects.get(id=int(identify))
        profile_to_json = {'msg': "<div class='col-xs-12"
                                  " bg-success prof_updated'>"
                                  "Profile has been updated</div>",
                           'image_src': profile.photo.url
                           if profile.photo else ''}
    else:
        profile_to_json = {'msg': "<div class='col-xs-12"
                                  " bg-danger prof_updated'>"
                                  "Profile is not updated</div>",
                           'image_src': profile.photo.url
                           if profile.photo else ''}

    return HttpResponse(json.dumps(profile_to_json),
                        content_type="application/json")


def login_view(request):
    form = LoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username,
                            password=password)
        if user is not None:
            login(request, user)
            profile = Profile.objects.get(user__username=username)
            request.session['user_id'] = profile.id
        else:
            profile = False
        profile_to_json = {'is_ok': True} if profile else {'is_ok': False}
        return HttpResponse(json.dumps(profile_to_json),
                            content_type="application/json")

    return render(request, 'task/login.html', dict(form=form))


@login_required(login_url='/login/')
def logout_view(request):
    logout(request)
    return HttpResponse(status=200)

templates/task/edit_profile.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head %}
    <meta name="keywords" content="">
    <meta name="description" content="">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/jquery-ui.theme.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/jquery-ui.structure.min.css' %}" />
    <script type="text/javascript" src="{% static 'js/jquery_upload_plugin.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.validate.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.ui.core.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui-datepicker.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>

    <title>Edit profile</title>
{% endblock %}
{% block content %}
    <div class="indicator"><img src="{% static 'images/indicator.gif' %}"> </div>
    <div class="container">
        <div id="test_name" class="col-xs-8 col-xs-offset-2 text-center"><h1>42 Coffee Cups Test Assignment</h1></div>
        <div class="row">
            <div class="col-xs-11 main-div">
                <div class="row">
                    <div class='logged_in_greeting col-xs-12'>
                        <div class='row'>
                            <div class='logged_in_greeting_title col-xs-10'>
                                <form action="{% url 'task:update_profile' %}" method="post" id="update-profile-form" enctype="multipart/form-data">
                                    {{ user_form.id }}
                                    <div class="col-xs-6 left-column">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <label >{{ user_form.name.label }}</label>
                                            {{ user_form.name }}
                                        </div>
                                        <div class="form-group">
                                            <label >{{ user_form.last_name.label }}</label>
                                            {{ user_form.last_name }}
                                        </div>
                                        <div class="form-group">
                                            <label >{{ user_form.date_of_birth.label }}</label>
                                            {{ user_form.date_of_birth }}
                                        </div>
                                        <div class="form-group">
                                            {{ user_form.photo }}
                                        </div>
                                        <div class="div_image_preview" {% if profile.photo  %} {% else %} img="no-img" {% endif %}>
                                            {% if profile.photo  %}
                                                <img id="image_preview" width="200"  src="{{ profile.photo.url }}">
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="col-xs-6 right_column">
                                        <div class="form-group">
                                            <label >{{ user_form.email.label }}</label>
                                            {{ user_form.email }}
                                        </div>
                                        <div class="form-group">
                                            <label >{{ user_form.jabber.label }}</label>
                                            {{ user_form.jabber }}
                                        </div>
                                        <div class="form-group">
                                            <label >{{ user_form.skype.label }}</label>
                                            {{ user_form.skype }}
                                        </div>
                                        <div class="form-group">
                                            <label >{{ user_form.other_contacts.label }}</label>
                                            {{ user_form.other_contacts }}
                                        </div>
                                        <div class="form-group">
                                            <label >{{ user_form.bio.label }}</label>
                                            {{ user_form.bio }}
                                        </div>
                                    </div>
                                    <input class="btn-group btn" type="submit" value="Save">
                                    <a class="btn-group btn"  href="{% url 'task:index' %}">Cancel</a>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/task/entry_tasks.html
 {% load endless %}
 {% paginate 10 task %}
{% for item in task %}
    <div id="{{ item.id }}" class="ui-state-default task_item" priority="{{ item.priority }}">
        <div class="task-title title-parent col-xs-4">
            <div class="task-title">Title: </div><div class="task-title-name">{{ item.title }}</div>
        </div>
        <div class="col-xs-4">
            <div class="task-title">Pub_date: </div><div class="task-status">{{ item.pub_date }}</div>
        </div>
        <div class="col-xs-2 status-parent col-xs-offset-2">
            <div class="task-title">Status: </div><div class="task-status" status="{{ item.status }}">{{ item.get_status_display }}</div>
        </div>
        <div class="col-xs-12 description-parent">
            <div class="task-description-title">Description</div><div class="task-description">{{ item.description }}</div>
        </div>
        <div class="col-xs-12"><button onclick="edit_form(this)" id="{{ item.id }}"class="btn btn-default task_edit_button">Edit task</button></div>
        <div class="col-xs-12 task_hr"></div>
    </div>
{% empty %}
    <div class="col-xs-6 col-xs-offset-3 text-danger"><h2 class="text-center">There are no tasks</h2></div>
{% endfor %}
{% show_more %}

templates/task/login.html
{% extends "base.html" %}
{% load staticfiles %}
{% load assets %}
{% block head %}
    <meta name="keywords" content="">
    <meta name="description" content="">
    <link rel="stylesheet" href="{% static 'bootstrap-3.3.5-dist/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script type="text/javascript" src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
    <title>Main</title>
{% endblock %}
{% block content %}
    <div class="indicator"><img src="{% static 'images/indicator.gif' %}"> </div>
    <div class="container">
        <div id="test_name" class="col-xs-8 col-xs-offset-2 text-center"><h1>42 Coffee Cups Test Assignment</h1></div>
        <div class="row">
            <div class="col-xs-12 main-div">
                <div class="login-div col-xs-6 col-xs-offset-3 main-login-div">
                    <div class="row">
                        <div class="col-xs-12 text-center">
                            <div class="prompt">
                                <div>username - admin</div>
                                <div>password - admin</div>
                            </div>
                            {% if messages %}
                                <ul class="messages list-unstyled">
                                    {% for message in messages %}
                                        <li{% if message.tags %} class="text-{{ message.tags }}"{% endif %}>{{ message }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                            <div class="login-form-title">Login</div>
                            <form id="login_form" action="/login/" method="post">
                                {% csrf_token %}
                                {{ form }}
                                <input class="btn" type="submit" value="submit">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/task/main.html
{% extends "base.html" %}
{% load staticfiles %}
{% load task_tags %}
{% block head %}
    <meta name="keywords" content="">
    <meta name="description" content="">
    <title>Main</title>
{% endblock %}
{% block content %}
    <div class="indicator"><img src="{% static 'images/indicator.gif' %}"> </div>
    <div class="container">
        <div id="test_name" class="col-xs-8 col-xs-offset-2 text-center"><h1>42 Coffee Cups Test Assignment</h1></div>
        <div class="row">
            <div class="col-xs-2 pull-right">
                <div class="authenticated-div">
                    {% if user.is_authenticated %}
                        <div class="logout-div">
                            <a href='{% url 'task:logout' %}'>Logout</a>
                        </div>
                        <div class="header_link"><a href='{% url 'task:edit_profile' %}'>Edit</a></div>
                        <a href='{% edit_link profile %}'>(admin)</a>
                        <div class="tasts_link"><a href="{% url 'task:tasks' %}">Tasks</a></div>
                    {% else %}
                        <div class="logout-div">
                            <a href='{% url 'task:login' %}'>Login</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-xs-11 main-div">
            <div class="row">
                <div class='logged_in_greeting col-xs-12'>
                    <div class='row'>
                        <div class='logged_in_greeting_title col-xs-10'>
                            <div class="user-data">
                                <div class="col-xs-6 left-column">
                                    <div class="field">{{ profile.name }}</div>
                                    <div class="field">{{ profile.last_name }}</div>
                                    <div class="field">{{ profile.date_of_birth }}</div>
                                    <div class="div_image_preview">
                                        {% if profile.photo  %}
                                            <img id="image_preview" width="200"  src="{{ profile.photo.url }}">
                                            {% else %}
                                            <img id="image_preview" width="200"  src="{% static 'images/no-avatar.jpeg' %}">
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="col-xs-6 right_column">
                                    <div class="field">Email: {{ profile.email }}</div>
                                    <div class="field">Jabber: {{ profile.jabber }}</div>
                                    <div class="field">Skype: {{ profile.skype }}</div>
                                    <span>Other_contacts:</span>
                                    <div class="field">{{ profile.other_contacts|linebreaks }}</div>
                                    <span id="bio_title">Bio:</span>
                                    <div>{{ profile.bio|linebreaks }}</div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <div class="row">
                                <div class="col-xs-12 hr"></div>
                                <div class="col-xs-3">
                                    <a href="{% url 'task:request_list' %}">requests</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/task/task_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load endless %}
{% block head %}
    <meta name="keywords" content="">
    <meta name="description" content="">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui-1.9.2.custom.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.validate.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/get_form.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/sortable.js' %}"></script>
    <title>Task list</title>
{% endblock %}
{% block content %}
    {% if messages %}
        <div class="django-message-main-div">
            {% for message in messages %}
                <div{% if message.tags %} class="alert-{{ message.tags }} django-message"{% endif %}>{{ message }}</div>
            {% endfor %}
        </div>
    {% endif %}
    <div class="indicator"><img src="{% static 'images/indicator.gif' %}"> </div>
    <div class=container>
        <div class="row">
            <div id="test_name" class="col-xs-8 col-xs-offset-2 text-center"><h1>42 Coffee Cups Test Assignment</h1></div>
            <div id="test_name" class="col-xs-8 col-xs-offset-2 text-center"><h2>Create Task</h2></div>
            <div class="col-xs-1 col-xs-offset-1"><a href="{% url 'task:index' %}">Main page</a></div>
            <div class="col-xs-12">
                <div class="col-xs-12">
                    <form id="create_task_form" method="POST" action="{% url 'task:tasks' %}">
                        {% for field in form %}
                            {% csrf_token %}
                            {% if field.errors %}
                                <div class="form-group error">
                                    <label class="control-label">{{ field.label }}</label>
                                    <div class="controls">{{ field }}
                        <span class="help-inline">
                            {% for error in  field.errors %}{{ error }}{% endfor %}
                        </span>
                                    </div>
                                </div>
                            {% else %}
                                <div class="form-group">
                                    <label class="control-label">{{ field.label }}</label>
                                    <div class="controls">{{ field }}
                                    </div>
                                </div>
                            {% endif %}
                        {% endfor %}
                        <input type="submit" class="btn task_create_button" value="Create task">
                    </form>
                </div>
                <div id="test_name" class="col-xs-8 col-xs-offset-2 text-center"><h2>Tasks</h2></div>
             <div class="sortable col-xs-12 clearfix">

                {% include page_template %}

                {% block js %}
                    {{ block.super }}
                    <script src="{{ STATIC_URL }}endless_pagination/js/endless-pagination.js"></script>
                    <script>$.endlessPaginate({paginateOnScroll: true});</script>
                {% endblock %}
        </div>
    </div>
    </div>
{% endblock %}